# Generated by Django 4.1.7 on 2023-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_messages_t_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='f_user',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
